apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-nats-pv-01
  namespace: nats
  labels:
    name: dev-nats-pv-01
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name:  nats-js-pvc-nats-0
    namespace: nats
  iscsi:
    targetPortal: 127.0.0.1:3260
    iqn: iqn.2000-01.com.synology:dev-nats-01
    lun: 2
    fsType: ext4
    readOnly: false
    chapAuthSession: true
    secretRef:
      name: pv-iscsi-chap-nats-secret
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-nats-pv-02
  namespace: nats
  labels:
    name: nats-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name:  nats-js-pvc-nats-1
    namespace: nats
  iscsi:
    targetPortal: 127.0.0.1:3260
    iqn: iqn.2000-01.com.synology:dev-nats-02
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthSession: true
    secretRef:
      name: pv-iscsi-chap-nats-secret
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-nats-pv-03
  namespace: nats
  labels:
    name: dev-nats-pv-03
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name:  nats-js-pvc-nats-2
    namespace: nats
  iscsi:
    targetPortal: 127.0.0.1:3260
    iqn: iqn.2000-01.com.synology:dev-nats-03
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthSession: true
    secretRef:
      name: pv-iscsi-chap-nats-secret