---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats.fullname" . }}
  namespace: {{ include "nats.namespace" . }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
  {{- if .Values.serviceAnnotations}}
  annotations:
    {{- toYaml .Values.serviceAnnotations | nindent 4 }}
  {{- end }}
spec:  
  type: {{ .Values.service.type }}
  selector:
    {{- include "nats.selectorLabels" . | nindent 4 }}    
  publishNotReadyAddresses: true
  {{- if .Values.topologyKeys }}
  topologyKeys:
    {{- toYaml .Values.topologyKeys | nindent 4 }}
  {{- end }}
  ports:
  {{- if .Values.websocket.enabled }}
  - name: websocket
    port: {{ .Values.websocket.port }}
    {{- if .Values.appProtocol.enabled }}
    appProtocol: tcp
    {{- end }}
  {{- end }}
  {{- if .Values.nats.profiling.enabled }}
  - name: profiling
    port: {{ .Values.nats.profiling.port }}
    {{- if .Values.appProtocol.enabled }}
    appProtocol: http
    {{- end }}
  {{- end }}
  - name: {{ .Values.nats.client.portName }}
    port: {{ .Values.nats.client.port }}
    {{- if .Values.appProtocol.enabled }}
    appProtocol: tcp
    {{- end }}
    {{- if and ((eq .Values.service.type "NodePort")) (not (empty .Values.service.client.nodePort)) }}
    nodePort: {{ .Values.service.client.nodePort }}
    {{- end }}
  - name: cluster
    port: 6222
    {{- if .Values.appProtocol.enabled }}
    appProtocol: tcp
    {{- end }}
    {{- if and ((eq .Values.service.type "NodePort")) (not (empty .Values.service.cluster.nodePort)) }}
    nodePort: {{ .Values.service.cluster.nodePort }}
    {{- end }}
  - name: monitor
    port: 8222
    {{- if .Values.appProtocol.enabled }}
    appProtocol: http
    {{- end }}
    {{- if and ((eq .Values.service.type "NodePort")) (not (empty .Values.service.monitor.nodePort)) }}
    nodePort: {{ .Values.service.monitor.nodePort }}
    {{- end }}
  - name: metrics
    port: 7777
    {{- if .Values.appProtocol.enabled }}
    appProtocol: http
    {{- end }}
    {{- if and ((eq .Values.service.type "NodePort")) (not (empty .Values.service.metrics.nodePort)) }}
    nodePort: {{ .Values.service.metrics.nodePort }}
    {{- end }}
  - name: leafnodes
    port: 7422
    {{- if .Values.appProtocol.enabled }}
    appProtocol: tcp
    {{- end }}
  - name: gateways
    port: 7522
    {{- if .Values.appProtocol.enabled }}
    appProtocol: tcp
    {{- end }}
  {{- if .Values.mqtt.enabled }}
  - name: mqtt
    port: 1883
    {{- if .Values.appProtocol.enabled }}
    appProtocol: tcp
    {{- end }}
  {{- end }}
